global:
  scrape_interval: 1m
  scrape_timeout: 10s
scrape_configs:
  - job_name: 'poorman_monitoring_system'
    scrape_interval: 1m
    honor_labels: true
    static_configs:
      - targets: ['192.168.50.187:9091']